name: Extract content to Notion

on:
  schedule:
    - cron: '0 */2 * * *'   # every 2 hours
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r projeto_linkedin/drop-news-main/cybersecurity-daily-feed/requirements.txt
      - name: Extract feeds → Notion (with Groq rewrite)
        env:
          NOTION_API_TOKEN: $${{ secrets.NOTION_API_TOKEN }}
          GROQ_API_KEY: $${{ secrets.GROQ_API_KEY }}
        run: |
          python projeto_linkedin/drop-news-main/cybersecurity-daily-feed/sec-feed-extract.py
